services:
  zigx_nuhu_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "zigx.nuhu.dev"
    restart: unless-stopped
    networks:
      - npm

networks:
  npm:
    driver: bridge
